### ISSUE TITLE
EndOfStreamException when loading save

### ISSUE THREAD

**Issue by lqkhoo** [RF5-Research/Eliza#4]
Hello!

When loading a save file, I got the window popup about having an incompatible save. So I booted up Visual Studio to get a better look.

I noticed the startup project was set to Mac (which I'm assuming you're using). Just to make it clear, I'm running the Windows executable, if it makes any difference in testing etc.

To begin with, I commented out the try/catch in `MainForm.cs`, and from the stack trace, `BinarySerializer.ReadValue()` keeps running into the last case, which triggers `BinarySerializer.ReadObject()`, which the debugger reports having `fieldValue` of null, which calls `ReadValue()` again. Finally the cycle ends with `ReadList()` being called, which runs into the EndOfStreamException. I haven't really dug into the code, but I'm assuming it's reading sequentially but it didn't quite manage to match what it's looking for, so it ran off the buffer.

Would you like me to provide the save file?

<img width="1011" alt="scap" src="https://user-images.githubusercontent.com/2603573/130141127-ddeb70b2-396b-46c6-b063-a9ba9f3a1c9d.png">

**Comment by SinsofSloth** [comment]
Hi, I'm assuming you're on the latest version. The save editor does not support that version as of now, and this has been brought to my attention. I'm busy IRL, so I haven't been able to look into what they changed, which is why it reads beyond the buffer. I don't mind you sharing your save file for me to look into.

**Comment by lqkhoo** [comment]
Oh, so that's why. I'm on game version 1.0.7. Which version does the editor support currently?

- Here's a save from 1.0.7: https://drive.google.com/drive/folders/1WTkAkBBzyHhGsfy1adocTChsJayexail?usp=sharing

When poking around at first, I thought the game might be decrypting it differently (e.g. with a different iv), so I had a little Python script duplicating `decrypt()`. There's still obvious structure in the decrypted data so they didn't alter that part at least.

If you could share your save as well, I could have the game update it to version 1.0.7. I could then diff the decrypted data sections to hunt for structural changes in a hex editor, perhaps in the coming weekend. Nothing other than game time and maybe character position should have been altered, so that should make it much easier.

**Comment by SinsofSloth** [comment]
The save editor only supports 1.0.6 and mainly 1.0.6 as of writing, as it doesn't do legacy support. I have attached my save files below. I also attached a template for 010-Editor that you can use to look into the save files in-depth and compare, as that's what the save editor is based off. I apologize for the lack of debugging support in the serialization, as the save editor is not a huge focus of mine.
[files.zip](https://github.com/RF5-Research/Eliza/files/7018841/files.zip)
[010-Templates.zip](https://github.com/RF5-Research/Eliza/files/7018844/010-Templates.zip)

**Comment by lqkhoo** [comment]
Thanks! I'll have a look.

**Comment by lqkhoo** [comment]
A quick question: When looking at the serializer, [line 187](https://github.com/RF5-Research/Eliza/blob/56b9fb0d13a0b918b1a1513dc19b79377e681f1e/Eliza/Core/Serialization/BinarySerializer.cs#L187), I noticed that instead of reproducing the last 4 bytes in the original footer, we're just writing zeros into them.

I re-implemented the top level serialization in Python, and the last 4 bytes are failing a unit test. The test is checking if we could get back the original file, and one of those bytes is usually not zero. I don't have v1.0.6 of the game to test with, but I'm assuming the game loads the file anyway?

I haven't gotten around to diffing v1.0.6 and v1.0.7 saves yet. However, that template file for 010-editor was super helpful! Did you get all that + the crypto and checksum functions via disassembly?

**Comment by SinsofSloth** [comment]
The game loads the file fine in v1.0.6, and the save editor accurately rewrote everything besides the padding, which is explained further down. The struct for the save data was taken from the game's global-metadata.dat, and to my knowledge it's just padding in the Footer-- they call it Blank-- so it's aligned. It's assumed that the padding is generated via RNG for the Footer padding and for the padding of the data that will be encrypted. And yes, this was mainly taken from disassembly and the global-metadata.dat to corroborate information.

**Comment by lqkhoo** [comment]
Making good progress.

However, I found an issue with the parsing of 1.0.6 files and I think that's more likely to be the problem, rather than cross-version changes. Using the release version of Eliza, try opening either rf5_gm001 or rf5_gm002 from your earlier link, from version 1.0.6. The serialization fails. The hex template fails as well.

The issue is with the first MESSAGEPACKOBJ, in the RF5STATUSDATA struct. You see, this is from rf5_gm000, which the hex template and Eliza parses properly. The next four bytes after the highlighted sequence corresponds to the following "Count" field of 32. That's really neat and nice.

<img width="1004" alt="scrcap" src="https://user-images.githubusercontent.com/2603573/130315014-8031d13f-7316-4739-88c5-06f958a4fbe5.png">

--

Now this is from rf5_gm001. The misalignment happened here. Notice the invalid "Count" field that follows. I'm not even sure where the "count" field is supposed to start. The following struct, HUMAN_STATUS_DATA, should start with 4 bytes of zero, corresponding to "npcId". However, even looking at the candidates, it's not obvious where the "count" field is supposed to be.

<img width="996" alt="scrcap2" src="https://user-images.githubusercontent.com/2603573/130315393-bdc6961a-9e52-47a5-a2fc-618c5012a7ad.png">


The same happens in rf_gm002 and rf_gm004, all with the same pattern of bytes.

A few things come to mind:
* In the second screenshot for rf5_gm001, it seems like there should be another 2 bytes to the MESSAGEPACKOBJ. It looks the same in rf5_gm002 as well. However, if we do that naively, it'll break parsing the first file.
* Still looking at rf5_gm001. Suppose we consider those two extra bytes in the MESSAGEPACKOBJ, i.e. the `CA 3F` should be part of it. The "count" field might be a 16-bit int, followed by another 2 bytes of I-don't-know-what. This makes the value in the "Count" field more reasonable, in the RF5_STATUS_DATA struct.

So I guess the main problem is what's the length of the MESSAGEPACKOBJ. I'll try to figure things out, but maybe you'd have a better clue from your experience, or the decompilation?

**Comment by lqkhoo** [comment]
There's another possibility. In the cases where the parsing fails, where the hex template thinks is the start of the MESSAGEPACKOBJ, it looks an awful lot like the "Count" field. In which case, I'm thinking the MESSAGEPACKOBJ may be completely absent?

Maybe test for if the first 4 bytes correspond to 32. I mean, the number of NPCs ought to be fixed. If it's not, then insert the 'unknown' MESSAGEPACKOBJ in between. That might be the fix, actually.

**Comment by lqkhoo** [comment]
Yes, I think that's it. It works on all the 1.0.6 files at least. It's a weird way of structuring data for sure. Here's a gist of how my Python script is parsing the files at the moment, using [Construct](https://construct.readthedocs.io/en/latest/index.html). I haven't uploaded the whole project to a repo.

See [line 410](https://gist.github.com/lqkhoo/f3735f9933b9ec2838083f7b0edcdfe2#file-model-py-L410)

Not immediately clear how I can update the hex template RF5.bt accordingly

**Comment by lqkhoo** [comment]
The difference between v1.0.6 and v1.0.7 is that they've added in 96 bytes at the end of the RF5_EVENTDATA struct. I don't know what these are, that's the only difference. Here's the hex template with the change. I just rolled them up into an integer array called 'unknown' so the rest of the file parses correctly.

[RF5_107.zip](https://github.com/RF5-Research/Eliza/files/7025358/RF5_107.zip)

I don't know to account for the MESSAGEPACKOBJ issue above, but the save files that I have for 1.0.7 aren't missing that bit in between, so it works for now. Here are more save files if you want to do some tests.

[107.zip](https://github.com/RF5-Research/Eliza/files/7025365/107.zip)

**Comment by SinsofSloth** [comment]
To clarify, the current release build is really old. I never updated builds there, as I was releasing it in a discord. I'm not sure if this resolves the message pack object issue you seemed to have, as if there was an issue, the template would have read beyond the EOF, which doesn't seem to be the case in your screenshots. I will look into global-metadata.dat whenever I can and just corroborate what you have, unless you want to do that.

**Comment by lqkhoo** [comment]
Alright, let me clarify:

To reproduce the issue in Eliza with v1.0.6 saves, do the following:
1. git clone from the default branch
2. build project from Visual Studio or from the CLI and run either the release or debug windows binary.
3. open "rf5_gm001", from the zip file you shared earlier. You'll get the error window. Same goes for 002 and 004.

I assumed it was the release version because that one's also 2 months old. I'm sorry if it caused any confusion.  If you decrypt those files and try to run the hex template on them, that fails as well.

I initially opened this issue because I was opening a save from 1.0.7, but this is from opening 1.0.6. What I wanted to share is that I think I might have figured out what's going wrong there.

Actually in the second screenshot, the hex template IS reading off EOF. The data struct was never completed, but 010-editor shows what it did manage to get (I'm on version 11) I just don't have room to show the end as I needed to show that huge int from the misalignment.

Right now I basically have a Python rewrite of Eliza.Core from troubleshooting this issue. With the modifications I mentioned, it is able to parse the 1.0.6 and 1.0.7 saves, at least all the ones that have been shared in this thread, by you and me both. I'm trying to see if that's really why we're getting EndOfStreamException in Eliza, because like you said, there's not much debugging information available from it.

I don't have access to global-metadata.dat, but I'm happy to take a look. Is that from the decompilation process? If you can provide some context of what that is, it'll be helpful.

I'm just a random guy who came across Eliza because I was simply looking to slap a couple of +10 rare cans into my backpack lol. Actually, I wanted to add items freely because I was building an item planner for RF5. I already built one for RF4 ([here](https://docs.google.com/spreadsheets/d/1t1Iwalk-37DV94X_c5FR5UAcfVyxnbRnccIxo0E_lZo/edit#gid=327209004)) that I shared on Reddit a year ago, but it's a spreadsheet. In RF4, the game handles rounding in a certain way, especially with mealy apple + object X interaction. I'm not at the point of the game where I can get certain items freely to test certain edge cases.

Thanks to the decrypted save and the hex template, I've worked out how the game encodes items, so right now I'm writing an item field parser so I don't have to mess around in hex.

Do let me know if I can help out with stuff that's not necessarily related to this particular issue as well.

Thanks for your help so far!

**Comment by SinsofSloth** [comment]
I apologize. After looking at the save files again, I realized they're from my old laptop. Thus, they're not v1.0.6. However, v1.0.4-1.0.6 to my knowledge is still supported by the save editor, as there was no changes made by the devs. If you look at the version of the files in the header, you'll see that the files that don't open are v1.0.2. I'll have to dump the romFS again in order to see what they changed whenever I have the chance and corroborate with what you have and name it properly. As for global-metadata.dat, that is from the romFS, and you can use https://github.com/Perfare/Il2CppDumper to dump the symbols.
If you prefer to continue this chat in Discord, you can just start a chat with me (Sloth#9454) or go to the RF reddit's [discord](https://discord.com/invite/zz5DjPQ) at #rf5-datamining. I appreciate your help as well. Thanks.
